server:
  port: 8099

spring:
  #  main:
  #    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://117.72.172.224:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    ollama:
      base-url: http://6ea7201d290e4c6aa00f-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-YqgAG0idUwN089vw1eE92b22F6Cf4dB3A84b1bB314A47b1f
      chat:
        options:
          model: gpt-4o
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    mcp:
      client:
        request-timeout: 360s
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config.json


logging:
  level:
    root: info
  config: classpath:logback-spring.xml
